api-version: v1Beta
environment:
  - key: EXCHANGE_ID
    value: autofill
  - key: EXCHANGE_INSTANCE
    value: prod
  - key: EXCHANGE_ACCOUNT
    value: 9019590001
  - key: EXTRA_OUTPUTS
    value: Position,BollingerBands,PnL
strategy:
  name: BollingerBands
  module: bbands1
  strategy-class: BollingerBandsStrategy1
  environment:
    - key: TRADING_INSTRUMENT
      value: PHEMEX:BTCUSD
    - key: BBANDS_BIN_MINUTES
      value: 5
    - key: BBANDS_WINDOW
      value: 20
    - key: BBANDS_NUM_STD
      value: 3
    - key: BBANDS_STOP_STD
      value: 2
    - key: BBANDS_QTY
      value: 100000
    - key: BBANDS_COOL_SECONDS
      value: 15