apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kibana
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    nodePort: 30601
    protocol: TCP
    targetPort: ui
  selector:
    app: kibana
