apiVersion: apps/v1
kind: Deployment
metadata:
  name: serenity-postfix
  labels:
    app: serenity-postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serenity-postfix
  template:
    metadata:
      labels:
        app: serenity-postfix
    spec:
      containers:
        - name: serenity-postfix
          image: cloudwallcapital/serenity-postfix:2020.12.19-b14
          ports:
          - containerPort: 25
---
apiVersion: v1
kind: Service
metadata:
  name: serenity-postfix
  labels:
    app: serenity-postfix
spec:
  ports:
  - port: 25
    protocol: TCP
  selector:
    app: serenity-postfix
